#!/usr/bin/env python3
"""Embed the maintained handbook chapters in the self-contained prompt.

Optionally synchronize the same chapters into the owning plugin repository.
This is text assembly, not a legal or behavioural validation.
"""

from __future__ import annotations

import argparse
import hashlib
import re
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
BEGIN = "<!-- BEGIN ZEUGNIS-HANDBUCH: generated by scripts/build_handbook.py -->"
END = "<!-- END ZEUGNIS-HANDBUCH -->"
CHAPTERS = (
    "arbeit-in-chat-plugin-und-word.md",
    "leistung-und-inhalt.md",
    "schluss-bindung-status.md",
    "form-fristen-durchsetzung.md",
)
INTRO = """## Vertiefendes Arbeitsbuch: Quellen, Fallführung und Umsetzung

Die folgenden Kapitel verbinden die am 08.10.2026 recherchierten Entscheidungen mit eigenständigen Arbeitshilfen. Entscheidungsbesprechung und eigene Anwendung sind getrennt: Rückfragen, Beispiele und Entwürfe sind keine wörtlichen Vorgaben der Gerichte. Die Recherche erfasst die bezeichneten Themen und Quellen, nicht jede veröffentlichte oder unveröffentlichte Entscheidung. Eine bloße Suchspur und ein nicht nachgewiesener Rechtsmittelstand bleiben ausdrücklich offen.

Die älteren Kurzanker im vorderen Teil dienen der Orientierung. Für die genaue Reichweite und den ausgewiesenen Quellenstatus gelten die differenzierten Besprechungen dieses Arbeitsbuchs. Nicht jede frühere Fundstelle wurde am neuen Stichtag erneut geprüft. Die dokumentierte Recherche ersetzt keine aktuelle Prüfung der im konkreten Mandat tragenden Quelle.

"""


def generated_block() -> str:
    chapters = [(ROOT / "handbuch" / name).read_text(encoding="utf-8").strip() for name in CHAPTERS]
    for index, (number, chapter) in enumerate(zip(range(20, 24), chapters)):
        if chapter.startswith(f"# {number}. "):
            chapter = re.sub(r"^(#{1,5}) ", r"#\1 ", chapter, flags=re.MULTILINE)
            chapters[index] = chapter
        if not chapter.startswith(f"## {number}. "):
            raise ValueError(f"Expected handbook chapter {number}")
    return BEGIN + "\n\n" + INTRO + "\n\n".join(chapters) + "\n\n" + END + "\n"


def embed(text: str, block: str) -> str:
    if BEGIN not in text and END not in text:
        return text.rstrip() + "\n\n" + block
    if text.count(BEGIN) != 1 or text.count(END) != 1:
        raise ValueError("Invalid handbook boundaries")
    before, remainder = text.split(BEGIN, 1)
    _, after = remainder.split(END, 1)
    return before + block.rstrip("\n") + after


def synchronize(path: Path, expected: str, check: bool) -> None:
    actual = path.read_text(encoding="utf-8") if path.exists() else None
    if actual == expected:
        return
    if check:
        raise ValueError(f"Stale generated content: {path}")
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(expected, encoding="utf-8")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--plugin-root", type=Path, help="Owning claude-fuer-deutsches-recht checkout")
    args = parser.parse_args()
    block = generated_block()
    skill_path = ROOT / "skill/SKILL.md"
    skill = embed(skill_path.read_text(encoding="utf-8"), block)
    synchronize(skill_path, skill, args.check)
    synchronize(ROOT / "docs/SKILL.md", skill, args.check)
    mini = (ROOT / "skill/SKILL-mini.md").read_text(encoding="utf-8")
    synchronize(ROOT / "docs/SKILL-mini.md", mini, args.check)

    count = len(skill.split())
    display_count = f"{count:,}".replace(",", ".")
    for relative in ("README.md", "docs/index.html"):
        path = ROOT / relative
        current = path.read_text(encoding="utf-8")
        expected = re.sub(r"\b[0-9]{1,3}(?:\.[0-9]{3})+ Wörter\b", f"{display_count} Wörter", current)
        synchronize(path, expected, args.check)

    # Preserve the existing artifact inventory; only recalculate its hashes.
    checksum_path = ROOT / "docs/SHA256SUMS.txt"
    entries = []
    for line in checksum_path.read_text(encoding="utf-8").splitlines():
        _, name = line.split("  ", 1)
        source = ROOT / "docs" / name
        if not source.is_file():
            source = ROOT / "docs/testakten" / name
        data = source.read_bytes()
        entries.append(f"{hashlib.sha256(data).hexdigest()}  {name}\n")
    synchronize(checksum_path, "".join(entries), args.check)

    if args.plugin_root:
        plugin = args.plugin_root.resolve() / "arbeitszeugnispruefer"
        workshop = plugin / "arbeitszeugnispruefer-werkstatt.md"
        if not workshop.is_file():
            raise ValueError("Not an existing Arbeitszeugnisprüfer plugin repository")
        synchronize(workshop, embed(workshop.read_text(encoding="utf-8"), block), args.check)
        reference = "# Arbeitszeugnis: vertiefendes Arbeitsbuch\n\n" + block
        synchronize(plugin / "references/arbeitszeugnis-handbuch.md", reference, args.check)

    print(f"Handbook {'checked' if args.check else 'assembled'}: {len(CHAPTERS)} chapters; full prompt {count:,} words.")


if __name__ == "__main__":
    main()
